User.create!([
  {email: "ddespala@gmail.com", password: "111111", first_name: "Domagoj", last_name: "Despalatovic", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, confirmation_token: "nWa7-jWsRwSxJK6Jhy2b", confirmed_at: "2021-05-09 23:49:32", confirmation_sent_at: "2021-05-09 23:49:21"},
  {email: "test@test.com", password: "111111", first_name: "matt", last_name: "murdock", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, confirmation_token: "R5yChvap8gTJqLmX7G9S", confirmed_at: "2021-05-09 23:50:31", confirmation_sent_at: "2021-05-09 23:50:20"}
])
Job.create!([
  {title: "Podmornicar", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "hrm", email: "hrm@hrm.com", category: "vojska", user_id: 2, slug: "podmornicar", created_at: "2021-03-09 23:49:32", updated_at: "2021-03-09 23:49:32"},
  {title: "Lutkar samostalan", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "Pinokio d.o.o.", email: "pinokio@gg.com", category: "lutkarstvo", user_id: 1, slug: "lutjar"},
  {title: "Klaun u cirkusu", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "cirkus d.o.o.", email: "cirkus@crks.com", category: "Fun Fun Fun", user_id: 1, slug: "klaun-u-cirkusu", created_at: "2021-03-09 23:49:32", updated_at: "2021-03-09 23:49:32"},
  {title: "Čistać taskova", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "ibm d.d.", email: "ibm@ibm.com", category: "Science", user_id: 1, slug: "cistac-taskova"},
  {title: "Spavač u salonu", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "Ikea d.d.", email: "ikea@ikea.com", category: "Sales", user_id: 2, slug: "spavac-u-salonu"},
  {title: "Hobit nosač prstena", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "Gandalf d.o.o.", email: "gandalf@gandalf.com", category: "Fantasy", user_id: 2, slug: "hobit-nosac-prstena"},
  {title: "Gurač stjene", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dictum risus nec dolor bibendum mollis. Duis scelerisque volutpat justo. Maecenas malesuada, sem a pharetra lobortis, mi metus laoreet purus, efficitur volutpat dui lorem ac ante. Suspendisse lobortis neque ut dui suscipit interdum. Sed placerat faucibus tellus sed commodo. Quisque convallis lorem ex, ac convallis nibh molestie vitae. Sed malesuada interdum mi, vitae suscipit nulla aliquet sed. Nullam efficitur justo vitae diam porttitor, vitae fringilla lectus ultrices. Aliquam erat volutpat. Nam enim nisl, finibus sit amet risus et, molestie efficitur nunc. Integer a nisi vel elit vulputate blandit nec et dolor. Aenean egestas diam quis ornare molestie. Morbi vestibulum a mi a ornare. Donec euismod dui eu elit dignissim cursus. Sed fringilla eros diam, porttitor sagittis massa aliquet ut. Sed dui mi, interdum nec venenatis a, egestas in diam.", employer: "Sizif d.o.o.", email: "sizif@sizif.com", category: "Turizam", user_id: 1, slug: "kurac-stjene"},
  {title: "Trnoružica po potrebi", description: "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"", employer: "Dvorac d.o.o.", email: "dvor@dvor.com", category: "Bajke", user_id: 1, slug: "trnoruzica-po-potrebi"},
  {title: "Kuhar", description: "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"", employer: "adada", email: "adwsdasd@ds.com", category: "food", user_id: 1, slug: "kuhar", created_at: "2021-03-09 23:49:32", updated_at: "2021-03-09 23:49:32"},
  {title: "Pilot spc", description: "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"", employer: "croatia airlines", email: "avion@gmail.com", category: "travel", user_id: 2, slug: "pilot-spc", created_at: "2021-03-09 23:49:32", updated_at: "2021-03-09 23:49:32"},
  {title: "Ronioc", description: "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"", employer: "roni d.o.o.", email: "roni@roni.com", category: "Gnjurac", user_id: 1, slug: "ronioc"}
])
Application.create!([
  {first_name: "Domagoj", last_name: "Despalatovic", born_on: "1998-02-11", email: "ddespala@gmail.com", phone: "0922137972", address: "Marticeva 31", education: "VSS", user_id: 1, job_id: 10, slug: "despalatovic-a0f19a3a-b9c3-43a7-8b6b-3130e4bfbd35"},
  {first_name: "matt", last_name: "murdock", born_on: "1999-01-01", email: "test2@test.com", phone: "0924552050", address: "Ulica 22", education: "VSS", user_id: 2, job_id: 11, slug: "murdock"},
  {first_name: "Domagoj", last_name: "Despalatovic", born_on: "1998-02-11", email: "ddespala@gmail.com", phone: "0922137972", address: "Marticeva 31", education: "VSS", user_id: 1, job_id: 10, slug: "despalatovic"}
])
ActiveStorage::Blob.create!([
  {key: "781sd51p9slpeb2fhskaakjrldfx", filename: "CV-domagoj-DP_compressed.pdf", content_type: "application/pdf", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 681636, checksum: "QYkBHjoGBpX83EaP6F3ZlA=="}
])
ActiveStorage::Attachment.create!([
  {name: "cv_file", record_type: "Application", record_id: 1, blob_id: 1}
])
